name: build_and_test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        variant: [
          { "python-version": "3.11", "pinned": true},
          { "python-version": "3.12", "pinned": true},
          { "python-version": "3.13", "pinned": true},
          { "python-version": "3.14", "pinned": true},
          { "python-version": "3.14", "pinned": false},
        ]

    steps:
      - uses: actions/checkout@v7
        with:
          # Need to clone everything for the git tags.
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          version: "0.12.5"
          python-version: ${{ matrix.variant.python-version }}
          enable-cache: true

      # Postgres-14 is already installed from official postgres repo, but we
      # also need pgsphere which is not installed. The repo is not in the list,
      # so we need to re-add it first.
      - name: Install postgresql (server)
        run: |
          sudo sh -c \
            'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-14 postgresql-14-pgsphere

      # Usually it makes sense to use library versions from the lockfile, so
      # you are testing the PR against a known-good build.  However,
      # we also add a non-required test against the latest version of libraries
      # so we get early warning if there are problems.
      - name: Upgrade all dependencies in lockfile
        run: uv lock --upgrade
        if: matrix.variant.pinned == false

      - name: Build and install
        run: uv sync --locked --all-extras --dev

      - name: List installed packages
        run: uv tree

      - name: Run tests
        shell: bash -l {0}
        env:
          SQLALCHEMY_WARN_20: 1
        run: |
          uv run pytest -Wd -r a -v -n 3 --cov=lsst.daf.butler --cov=tests --cov-report=xml --cov-report=term --cov-branch \
            --junitxml=junit.xml -o junit_family=legacy
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v7
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v7
        with:
          report_type: test_results
          token: ${{ secrets.CODECOV_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    needs: [build_and_test]
    # The "not starts with 's'" is meant to catch server release tags in the
    # form 'server/x.y.z'
    if: startsWith(github.ref, 'refs/tags') && ! startsWith(github.ref, 'refs/tags/s')

    steps:
      - uses: actions/checkout@v7
        with:
          # Need to clone everything to embed the version.
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools wheel build

      - name: Build and create distribution
        run: |
          python -m build --skip-dependency-check

      - name: Upload
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_UPLOADS }}
